### ISSUE TITLE
As an AirViewer2 User, should be able to convert the pdf into Various formats such as HTML, Text File and Document so that based on the requirement user can convert the pdf into his desired format.

### ISSUE THREAD

**Issue by rahul-satla** [TeamAlpha5/AirViewer2#5]

**Comment by rahul-satla** [comment]
Tasks for this User Story:

## Todo

- [ ]  As a part of issue 5, Write a function that converts PDF to Doc

- [ ]   As a part of issue 5, Write a function that converts PDF to Text

- [ ] As a part of issue 5, Write a function that converts PDF to HTML

- [ ] As a part of issue 5, I should add the UI buttons so that the user can convert their required pdf into file formats

- [ ] As a part of issue 5, I should test the functionality of the code which converts PDF to Doc with appropriate test cases 

- [ ] As a part of issue 5, I should test the functionality of the code which converts PDF to text with appropriate test cases

- [ ] As a part of issue 5, I should test the functionality of the code which converts PDF to HTML with appropriate test cases

- [ ] As a part of issue 5, I should add all the dependencies which are required for converting PDF to file formats
